export const tooltipDataApi = [
  {
    id: 1,
    propsName: "title",
    propsType: "string",
    propsDescription: "Title of the tooltip.",
    default: "Tooltip Text",
  },
  {
    id: 2,
    propsName: "children",
    propsType: "ReactNode",
    propsDescription: "Child elements to trigger the tooltip.",
    default: "<Button/>",
  },
  {
    id: 3,
    propsName: "content",
    propsType: "ReactNode",
    propsDescription: "Content of the tooltip.",
    default: "Text",
  },
  {
    id: 4,
    propsName: "placement",
    propsType: ["top", "bottom", "left", "right"],
    propsDescription: "Placement of the tooltip.",
    default: "top",
  },
  {
    id: 5,
    propsName: "trigger",
    propsType: ["hover", "click"],
    propsDescription: "Trigger mode for displaying the tooltip.",
    default: "hover",
  },
  {
    id: 6,
    propsName: "style",
    propsType: ["dark", "light"],
    propsDescription: "Style of the tooltip.",
    default: "dark",
  },
  {
    id: 7,
    propsName: "animation",
    propsType: "false | `duration-${number}`",
    propsDescription: "Animation duration class for the tooltip.",
    default: "false",
  },
  {
    id: 8,
    propsName: "arrow",
    propsType: "boolean",
    propsDescription: "Show or hide the tooltip arrow sign.",
    default: "true",
  },
];
