export const buttonApiData = [
  {
    id: 1,
    propsName: "href",
    propsType: "string",
    propsDescription: "URL to navigate when the button is clicked.",
    default: "None",
  },
  {
    id: 2,
    propsName: "color",
    propsType: ["error", "info", "success", "warning"],
    propsDescription: "Color variant of the button",
    default: "info",
  },
  {
    id: 3,
    propsName: "type",
    propsType: [
      "primary",
      "dashed",
      "text",
      "linkPrimary",
      "linkGray",
      "outlineGray",
      "outlinePrimary",
      "default",
    ],
    propsDescription: "Type of the button.",
    default: "default",
  },
  {
    id: 4,
    propsName: "notificationLabel",
    propsType: "string",
    propsDescription: "Label for notification badge on the button.",
    default: "None",
  },
  {
    id: 5,
    propsName: "pill",
    propsType: "boolean",
    propsDescription: "Apply pill-shaped styling to the button.",
    default: "false",
  },
  {
    id: 6,
    propsName: "circle",
    propsType: "boolean",
    propsDescription: "Apply circular styling to the button.",
    default: "false",
  },
  {
    id: 7,
    propsName: "positionInGroup",
    propsType: ["start", "end", "middle"],
    propsDescription: "Position of the button within a button group.",
    default: "start",
  },

  {
    id: 9,
    propsName: "size",
    propsType: ["xs", "sm", "md", "lg", "xl", "2xl"],
    propsDescription: "Size variant of the button.",
    default: "md",
  },
  {
    id: 10,
    propsName: "width",
    propsType: ["full", "half"],
    propsDescription: "Width of the button",
    default: "half",
  },
  {
    id: 11,
    propsName: "customClass",
    propsType: "string",
    propsDescription: "Custom CSS class to be added to the button.",
    default: "None",
  },
  {
    id: 12,
    propsName: "onClick",
    propsType: "() => void",
    propsDescription: "Function to be called when the button is clicked.",
    default: "function",
  },
];
