export const tagApiData = [
  {
    id: 1,
    propsName: "leftIcon",
    propsType: "ReactNode",
    propsDescription: "Icon component displayed on the left side of the tag.",
    default: "<CrownSimple/>",
  },
  {
    id: 2,
    propsName: "dismissIcon",
    propsType: "ReactNode",
    propsDescription: "Icon component used for dismissing the tag.",
    default: "<X/>",
  },
  {
    id: 3,
    propsName: "dismiss",
    propsType: "Boolean",
    propsDescription: "Determines if the tag can be dismissed.",
    default: "false",
  },
  {
    id: 4,
    propsName: "disabled",
    propsType: "Boolean",
    propsDescription: "Disables interactions with the tag.",
    default: "false",
  },
  {
    id: 5,
    propsName: "color",
    propsType: [
      "error",
      "gray",
      "info",
      "success",
      "warning",
      "teal",
      "purple",
    ],
    propsDescription: "Specifies the color variant of the tag.",
    default: "gray",
  },
  {
    id: 6,
    propsName: "borderType",
    propsType: ["solid", "dashed"],
    propsDescription: "Sets the type of border for the tag.",
    default: "solid",
  },
  {
    id: 7,
    propsName: "onDismiss",
    propsType: "boolean | (() => void)",
    propsDescription: "Callback function when the tag is dismissed.",
    default: "Function",
  },
];
