interface routerPath {
  id: number;
  name: string;
  href: string;
  tag?: boolean;
  deprecate?: boolean;
}

export const routes: routerPath[] = [
  {
    id: 1,
    name: "Accordion",
    href: "/docs/components/accordion",
    tag: false,
    deprecate: false,
  },
  {
    id: 2,
    name: "Alert",
    href: "/docs/components/alert",
    tag: false,
    deprecate: false,
  },
  {
    id: 3,
    name: "Area Chart",
    href: "/docs/components/areaChart",
    tag: false,
    deprecate: false,
  },
  {
    id: 4,
    name: "Avatar",
    href: "/docs/components/avatar",
    tag: false,
    deprecate: false,
  },
  {
    id: 5,
    name: "Avatar Group",
    href: "/docs/components/avatarGroup",
    tag: false,
    deprecate: false,
  },
  {
    id: 6,
    name: "Badge",
    href: "/docs/components/badge",
    tag: false,
    deprecate: false,
  },
  {
    id: 43,
    name: "Bar Chart",
    href: "/docs/components/barChart",
    tag: false,
    deprecate: false,
  },
  {
    id: 7,
    name: "BreadCrumb",
    href: "/docs/components/breadcrumb",
    tag: false,
    deprecate: false,
  },
  {
    id: 8,
    name: "Button",
    href: "/docs/components/button",
    tag: false,
    deprecate: false,
  },
  {
    id: 9,
    name: "Button Group",
    href: "/docs/components/buttonGroup",
    tag: false,
    deprecate: false,
  },
  {
    id: 10,
    name: "Card",
    href: "/docs/components/card",
    tag: false,
    deprecate: false,
  },
  {
    id: 11,
    name: "Carousel",
    href: "/docs/components/carousel",
    tag: false,
    deprecate: false,
  },
  {
    id: 12,
    name: "CheckBox",
    href: "/docs/components/checkbox",
    tag: false,
    deprecate: false,
  },
  {
    id: 13,
    name: "CheckBox Group",
    href: "/docs/components/checkboxGroup",
    tag: false,
    deprecate: false,
  },
  {
    id: 14,
    name: "Date Picker",
    href: "/docs/components/datePicker",
    tag: false,
    deprecate: false,
  },
  {
    id: 15,
    name: "Dropdown",
    href: "/docs/components/dropdown",
    tag: false,
    deprecate: false,
  },
  {
    id: 16,
    name: "Empty",
    href: "/docs/components/empty",
    tag: false,
    deprecate: false,
  },
  {
    id: 17,
    name: "Modal",
    href: "/docs/components/modal",
    tag: false,
    deprecate: false,
  },
  {
    id: 18,
    name: "Navbar",
    href: "/docs/components/navbar",
    tag: false,
    deprecate: false,
  },
  {
    id: 19,
    name: "Notification",
    href: "/docs/components/notification",
    tag: false,
    deprecate: false,
  },
  {
    id: 20,
    name: "Number Input",
    href: "/docs/components/numberInput",
    tag: false,
    deprecate: false,
  },
  {
    id: 21,
    name: "Play Button",
    href: "/docs/components/playButton",
    tag: false,
    deprecate: false,
  },
  {
    id: 22,
    name: "Progress",
    href: "/docs/components/progress",
    tag: false,
    deprecate: false,
  },
  {
    id: 44,
    name: "Pagination",
    href: "/docs/components/pagination",
    tag: false,
    deprecate: false,
  },
  {
    id: 23,
    name: "Radio",
    href: "/docs/components/radio",
    tag: false,
    deprecate: false,
  },
  {
    id: 24,
    name: "Rating",
    href: "/docs/components/rating",
    tag: false,
    deprecate: false,
  },
  {
    id: 25,
    name: "Search Bar",
    href: "/docs/components/searchBar",
    tag: false,
    deprecate: false,
  },
  {
    id: 26,
    name: "Sidebar",
    href: "/docs/components/sidebar",
    tag: false,
    deprecate: false,
  },
  {
    id: 27,
    name: "Skeleton",
    href: "/docs/components/skeleton",
    tag: false,
    deprecate: false,
  },
  {
    id: 28,
    name: "Slider",
    href: "/docs/components/slider",
    tag: false,
    deprecate: false,
  },
  {
    id: 29,
    name: "Spinner",
    href: "/docs/components/spinner",
    tag: false,
    deprecate: false,
  },
  {
    id: 30,
    name: "Statistic",
    href: "/docs/components/statistic",
    tag: false,
    deprecate: false,
  },
  {
    id: 31,
    name: "Steps",
    href: "/docs/components/step",
    tag: false,
    deprecate: false,
  },
  {
    id: 32,
    name: "Switch",
    href: "/docs/components/switch",
    tag: false,
    deprecate: false,
  },
  {
    id: 33,
    name: "Table",
    href: "/docs/components/table",
    tag: false,
    deprecate: false,
  },
  {
    id: 34,
    name: "Tabs",
    href: "/docs/components/tabs",
    tag: false,
    deprecate: false,
  },
  {
    id: 35,
    name: "Tag",
    href: "/docs/components/tag",
    tag: false,
    deprecate: false,
  },
  {
    id: 36,
    name: "Text Area",
    href: "/docs/components/textArea",
    tag: false,
    deprecate: false,
  },
  {
    id: 37,
    name: "Text Input",
    href: "/docs/components/textInput",
    tag: false,
    deprecate: false,
  },
  {
    id: 38,
    name: "Timeline",
    href: "/docs/components/timeline",
    tag: false,
    deprecate: false,
  },
  {
    id: 39,
    name: "Toast",
    href: "/docs/components/toast",
    tag: false,
    deprecate: false,
  },
  {
    id: 40,
    name: "Tooltip",
    href: "/docs/components/tooltip",
    tag: false,
    deprecate: false,
  },
  {
    id: 41,
    name: "Tree",
    href: "/docs/components/tree",
    tag: false,
    deprecate: false,
  },
  {
    id: 42,
    name: "Upload",
    href: "/docs/components/upload",
    tag: false,
    deprecate: false,
  },
];

export const gettingStartedRoutes: routerPath[] = [
  {
    id: 1,
    name: "Introduction",
    href: "/docs/getting-started/Introduction",
  },
  {
    id: 2,
    name: "Installation",
    href: "/docs/getting-started/Installation",
  },
];

export const navbarRoutes: routerPath[] = [
  {
    id: 1,
    href: "/home",
    name: "Home",
  },
  {
    id: 2,
    href: "/figma",
    name: "Figma",
  },
];
