export const carouselDataApi = [
  {
    id: 1,
    propsName: 'indicators',
    propsType: 'boolean',
    propsDescription: 'Whether to display indicators for carousel items.',
    default: 'false',
  },
  {
    id: 2,
    propsName: 'showControls',
    propsType: 'boolean',
    propsDescription: 'Whether to display navigation controls (Next/Previous).',
    default: 'true',
  },
  {
    id: 3,
    propsName: 'leftControl',
    propsType: 'ReactNode',
    propsDescription: 'Custom ReactNode to be used as the left navigation control.',
    default: 'Icon',
  },
  {
    id: 4,
    propsName: 'rightControl',
    propsType: 'ReactNode',
    propsDescription: 'Custom ReactNode to be used as the right navigation control.',
    default: 'Icon',
  },
  {
    id: 5,
    propsName: 'slide',
    propsType: 'boolean',
    propsDescription: 'Whether to enable automatic sliding of carousel items.',
    default: 'false',
  },
  {
    id: 7,
    propsName: 'indicatorsType',
    propsType: ['dot', 'ring', 'bar', 'square', 'squareRing'],
    propsDescription: 'Type of indicators to display.',
    default: 'dot',
  },
  {
    id: 8,
    propsName: 'indicatorsTypeColors',
    propsType: ['white', 'slate'],
    propsDescription: 'Color variant for the indicators based on the selected type.',
    default: 'white',
  },
  {
    id: 9,
    propsName: 'className',
    propsType: 'string',
    propsDescription: 'Custom class to be added to the carousel.',
    default: 'None',
  },
  {
    id: 10,
    propsName: 'config',
    propsType: 'Object<EmblaOptionsType>',
    propsDescription: 'Options for customizing the default carousel',
    default: '{}',
  },
]
