export const barChartAPIData = [
  {
    id: 1,
    propsName: 'active',
    propsType: 'boolean',
    propsDescription: 'Determines if the bar chart is active.',
    default: 'false',
  },
  {
    id: 2,
    propsName: 'activeColor',
    propsType: 'string',
    propsDescription: 'Color of the active bars.',
    default: '#1C222B',
  },
  {
    id: 3,
    propsName: 'activeIndex',
    propsType: 'number',
    propsDescription: 'Index of the currently active bar.',
    default: '5',
  },
  {
    id: 4,
    propsName: 'barBg',
    propsType: 'string',
    propsDescription: 'Background color of the bars.',
    default: '#F0F3F9',
  },
  {
    id: 5,
    propsName: 'barColor',
    propsType: 'string',
    propsDescription: 'Color of the bars.',
    default: '#1B4DFF',
  },
  {
    id: 6,
    propsName: 'barRadius',
    propsType: 'Array',
    propsDescription: 'Radius of the bar corners.',
    default: '[4,4,0,0]',
  },
  {
    id: 7,
    propsName: 'barSize',
    propsType: 'number',
    propsDescription: 'Size of the bars.',
    default: '32',
  },
  {
    id: 8,
    propsName: 'chartData',
    propsType: 'Array',
    propsDescription: 'Array of data for the chart.',
    default: 'Array',
  },
  {
    id: 9,
    propsName: 'dataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the primary data.',
    default: 'price',
  },
  {
    id: 10,
    propsName: 'height',
    propsType: 'number',
    propsDescription: 'Height of the chart.',
    default: '250',
  },
  {
    id: 11,
    propsName: 'inActiveColor',
    propsType: 'string',
    propsDescription: 'Color of the inactive bars.',
    default: '#1C222B',
  },
  {
    id: 12,
    propsName: 'secondaryBarBg',
    propsType: 'string',
    propsDescription: 'Background color of the secondary bars.',
    default: '#F0F3F9',
  },
  {
    id: 13,
    propsName: 'secondaryBarColor',
    propsType: 'string',
    propsDescription: 'Color of the secondary bars.',
    default: '#3D4A5C',
  },
  {
    id: 14,
    propsName: 'secondaryDataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the secondary data.',
    default: 'sell',
  },
  {
    id: 15,
    propsName: 'showBg',
    propsType: 'boolean',
    propsDescription: 'Determines if the chart background is visible.',
    default: 'false',
  },
  {
    id: 16,
    propsName: 'showGridLine',
    propsType: 'boolean',
    propsDescription: 'Determines if grid lines are visible.',
    default: 'false',
  },
  {
    id: 17,
    propsName: 'showLegend',
    propsType: 'boolean',
    propsDescription: 'Determines if the legend is visible.',
    default: 'false',
  },
  {
    id: 18,
    propsName: 'showTooltip',
    propsType: 'boolean',
    propsDescription: 'Determines if tooltips are visible.',
    default: 'false',
  },
  {
    id: 19,
    propsName: 'showXAxis',
    propsType: 'boolean',
    propsDescription: 'Determines if the X-axis is visible.',
    default: 'false',
  },
  {
    id: 20,
    propsName: 'showYAxis',
    propsType: 'boolean',
    propsDescription: 'Determines if the Y-axis is visible.',
    default: 'false',
  },
  {
    id: 21,
    propsName: 'width',
    propsType: 'number',
    propsDescription: 'Width of the chart.',
    default: '600',
  },
  {
    id: 22,
    propsName: 'XAxisDataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the X-axis data.',
    default: 'None',
  },
  {
    id: 23,
    propsName: 'YAxisDataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the Y-axis data.',
    default: 'None',
  },
  {
    id: 25,
    propsName: 'tooltipBtnStyle',
    propsType: 'string',
    propsDescription: 'Custom style of the tooltip.',
    default: 'None',
  },
]
