export const barChartAPIData = [
  {
    id: 1,
    propsName: "active",
    propsType: "boolean",
    propsDescription: "Determines if the bar chart is active.",
    default: "false",
  },
  {
    id: 2,
    propsName: "activeColor",
    propsType: "string",
    propsDescription: "Color of the active bars.",
    default: "#1B4DFF",
  },
  {
    id: 3,
    propsName: "activeIndex",
    propsType: "number",
    propsDescription: "Index of the currently active bar.",
    default: "5",
  },
  {
    id: 4,
    propsName: "barBackGroundColor",
    propsType: "string",
    propsDescription: "Background color of the bars.",
    default: "#E8EDFF",
  },
  {
    id: 5,
    propsName: "barColor",
    propsType: "string",
    propsDescription: "Color of the bars.",
    default: "#1B4DFF",
  },
  {
    id: 6,
    propsName: "barRadius",
    propsType: "number",
    propsDescription: "Radius of the bar corners.",
    default: "5",
  },
  {
    id: 7,
    propsName: "barSize",
    propsType: "number",
    propsDescription: "Size of the bars.",
    default: "6",
  },
  {
    id: 8,
    propsName: "chartData",
    propsType: "unknown[]",
    propsDescription: "Array of data for the chart.",
    default: "Array",
  },
  {
    id: 9,
    propsName: "dataKey",
    propsType: "string",
    propsDescription: "Key in the data array for the primary data.",
    default: "price",
  },
  {
    id: 10,
    propsName: "height",
    propsType: "number",
    propsDescription: "Height of the chart.",
    default: "250",
  },
  {
    id: 11,
    propsName: "inActiveColor",
    propsType: "string",
    propsDescription: "Color of the inactive bars.",
    default: "#1B4DFF",
  },
  {
    id: 12,
    propsName: "secondaryBarBackGroundColor",
    propsType: "string",
    propsDescription: "Background color of the secondary bars.",
    default: "#D7FFEB",
  },
  {
    id: 13,
    propsName: "secondaryBarColor",
    propsType: "string",
    propsDescription: "Color of the secondary bars.",
    default: "#1DB469",
  },
  {
    id: 14,
    propsName: "secondaryDataKey",
    propsType: "string",
    propsDescription: "Key in the data array for the secondary data.",
    default: "sell",
  },
  {
    id: 15,
    propsName: "showBackGround",
    propsType: "boolean",
    propsDescription: "Determines if the chart background is visible.",
    default: "false",
  },
  {
    id: 16,
    propsName: "showGridLine",
    propsType: "boolean",
    propsDescription: "Determines if grid lines are visible.",
    default: "false",
  },
  {
    id: 17,
    propsName: "showLegend",
    propsType: "boolean",
    propsDescription: "Determines if the legend is visible.",
    default: "false",
  },
  {
    id: 18,
    propsName: "showTooltip",
    propsType: "boolean",
    propsDescription: "Determines if tooltips are visible.",
    default: "false",
  },
  {
    id: 19,
    propsName: "showXaxis",
    propsType: "boolean",
    propsDescription: "Determines if the X-axis is visible.",
    default: "false",
  },
  {
    id: 20,
    propsName: "showYaxis",
    propsType: "boolean",
    propsDescription: "Determines if the Y-axis is visible.",
    default: "false",
  },
  {
    id: 21,
    propsName: "width",
    propsType: "number",
    propsDescription: "Width of the chart.",
    default: "500",
  },
  {
    id: 22,
    propsName: "XAxisDataKey",
    propsType: "string",
    propsDescription: "Key in the data array for the X-axis data.",
    default: "None",
  },
  {
    id: 23,
    propsName: "YAxisDataKey",
    propsType: "string",
    propsDescription: "Key in the data array for the Y-axis data.",
    default: "None",
  },
];
