export const sliderAPIData = [
  {
    id: 1,
    propsName: "min",
    propsType: "number",
    propsDescription: "Minimum value of the slider.",
    default: "0",
  },
  {
    id: 2,
    propsName: "max",
    propsType: "number",
    propsDescription: "Maximum value of the slider.",
    default: "100",
  },
  {
    id: 3,
    propsName: "step",
    propsType: "number",
    propsDescription:
      "Step size for each increment on the slider. Can be null.",
    default: "number",
  },
  {
    id: 4,
    propsName: "range",
    propsType: "boolean",
    propsDescription: "Determines whether the slider displays a range color.",
    default: "false",
  },
  {
    id: 5,
    propsName: "dots",
    propsType: "boolean",
    propsDescription: "Determines whether dots are displayed on the slider.",
    default: "false",
  },
  {
    id: 6,
    propsName: "marks",
    propsType: "Object",
    propsDescription: "Defines points on the slider with custom labels.",
    default: "Object",
  },
  {
    id: 7,
    propsName: "reverse",
    propsType: "boolean",
    propsDescription: "Determines if the slider values are shown in reverse.",
    default: "false",
  },
  {
    id: 8,
    propsName: "disabled",
    propsType: "boolean",
    default: "false",
    propsDescription: "Determines if the slider is disabled.",
  },
  {
    id: 12,
    propsName: "defaultValue",
    propsType: ["number", "number[]"],
    default: "0",
    propsDescription: "Initial default value or values for the slider.",
  },
  {
    id: 13,
    propsName: "onChange",
    propsType: "function",
    propsDescription: "Callback function when the slider value changes.",
    default: "(value) => void",
  },
  {
    id: 14,
    propsName: "tooltip",
    propsType: ["top", "bottom", "none"],
    propsDescription: "Specifies the position of the tooltip or hides it.",
    default: "top",
  },
];

// {
//     id: 9,
//     propsName: "pushable",
//     propsType: ["boolean", "number"],
//     default: "true",
//     propsDescription:
//       "Allows pushing neighboring handles. Can be boolean or number.",
//   },
//   {
//     id: 10,
//     propsName: "allowCross",
//     propsType: "boolean",
//     default: "false",
//     propsDescription: "Allows the handles to cross each other on the slider.",
//   },
//   {
//     id: 11,
//     propsName: "draggableTrack",
//     propsType: "boolean",
//     default: "false",
//     propsDescription: "Allows dragging the entire track to set values.",
//   },
