export const cardAPIData = [
  {
    id: 1,
    propsName: "shadow",
    propsType: "boolean",
    propsDescription: "Toggle the shadow effect for the card.",
    default: "false",
  },
  {
    id: 2,
    propsName: "border",
    propsType: "boolean",
    propsDescription: "Toggle the border for the card.",
    default: "false",
  },
  {
    id: 3,
    propsName: "horizontal",
    propsType: "boolean",
    propsDescription: "Display the card content horizontally.",
    default: "false",
  },
  {
    id: 4,
    propsName: "href",
    propsType: "string",
    propsDescription: "URL link for the card.",
    default: "None",
  },
  {
    id: 5,
    propsName: "imgAlt",
    propsType: "string",
    propsDescription: "Alt text for the card's background image.",
    default: "None",
  },
  {
    id: 6,
    propsName: "imgSrc",
    propsType: "string",
    propsDescription: "Source URL for the card's background image.",
    default: "URL",
  },
  {
    id: 7,
    propsName: "imgSize",
    propsType: ["sm", "md", "lg"],
    propsDescription: "Size of the card's background image.",
    default: "lg",
  },
];
