export const CheckBoxApiData = [
  {
    id: 1,
    propsName: 'size',
    propsType: ['sm', 'md', 'lg'],
    propsDescription: 'Available size options for checkbox.',
    default: 'md',
  },
  {
    id: 2,
    propsName: 'label',
    propsType: 'string',
    propsDescription: 'Checkbox label text',
    default: 'Checkbox',
  },
  {
    id: 3,
    propsName: 'color',
    propsType: ['info', 'warning', 'error', 'success'],
    propsDescription: 'Checkbox Color',
    default: 'info',
  },
  {
    id: 4,
    propsName: 'labelColor',
    propsType: ['info', 'warning', 'error', 'success'],
    propsDescription: 'Checkbox Color',
    default: 'info',
  },
  {
    id: 5,
    propsName: 'variant',
    propsType: ['square', 'circle'],
    propsDescription: 'Checkbox Variant',
    default: 'square',
  },
  {
    id: 6,
    propsName: 'id',
    propsType: 'string',
    propsDescription: 'Checkbox Input Field ID',
    default: 'one',
  },
  {
    id: 7,
    propsName: 'fieldName',
    propsType: 'string',
    propsDescription: 'Checkbox Input Field Name',
    default: 'checkbox',
  },
]
