export const progressDataApi = [
  {
    id: 9,
    propsName: "color",
    propsType: ["info", "error", "success", "warning", "indigo", "purple"],
    propsDescription: "Defines the available color options for progress.",
    default: "info",
  },
  {
    id: 1,
    propsName: "size",
    propsType: ["sm", "md", "lg", "xl"],
    propsDescription: "Defines the available sizes options for progress.",
    default: "md",
  },
  {
    id: 2,
    propsName: "label",
    propsType: "string",
    propsDescription: "Progress level text.",
    default: "Text",
  },
  {
    id: 3,
    propsName: "labelPosition",
    propsType: ["inside", "outside", "none"],
    propsDescription: "Defines the available position for progress label.",
    default: "outside",
  },
  {
    id: 4,
    propsName: "labelProgress",
    propsType: "boolean",
    propsDescription: "Specifies whether the progress label is shown.",
    default: "false",
  },
  {
    id: 5,
    propsName: "showPopupLabelProgress",
    propsType: "boolean",
    propsDescription: "Specifies whether the popup label progress is shown.",
    default: "false",
  },
  {
    id: 6,
    propsName: "rounded",
    propsType: "boolean",
    propsDescription: "Specifies whether the progress bar is rounded.",
    default: "false",
  },
  {
    id: 7,
    propsName: "bordered",
    propsType: "boolean",
    propsDescription: "Specifies whether the progress bar is bordered.",
    default: "false",
  },
  {
    id: 8,
    propsName: "progress",
    propsType: "number",
    propsDescription: "Defines the progress control for the progress bar.",
    default: "45",
  },
];
