export const lineChartAPIData = [
  {
    id: 1,
    propsName: 'chartData',
    propsType: 'Array',
    propsDescription: 'Array of data for the chart.',
    default: 'Array',
  },
  {
    id: 2,
    propsName: 'dataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the primary data.',
    default: 'price',
  },
  {
    id: 3,
    propsName: 'height',
    propsType: 'number',
    propsDescription: 'Height of the chart.',
    default: '250',
  },
  {
    id: 4,
    propsName: 'lineColor',
    propsType: 'string',
    propsDescription: 'Color of the first line.',
    default: '#1C222B',
  },
  {
    id: 5,
    propsName: 'secondaryLineColor',
    propsType: 'string',
    propsDescription: 'Color of the secondary line.',
    default: '#3D4A5C',
  },
  {
    id: 6,
    propsName: 'secondaryDataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the secondary data.',
    default: 'sell',
  },

  {
    id: 7,
    propsName: 'showGridLine',
    propsType: 'boolean',
    propsDescription: 'Determines if grid lines are visible.',
    default: 'false',
  },
  {
    id: 17,
    propsName: 'showLegend',
    propsType: 'boolean',
    propsDescription: 'Determines if the legend is visible.',
    default: 'false',
  },
  {
    id: 18,
    propsName: 'showTooltip',
    propsType: 'boolean',
    propsDescription: 'Determines if tooltips are visible.',
    default: 'false',
  },
  {
    id: 19,
    propsName: 'showXAxis',
    propsType: 'boolean',
    propsDescription: 'Determines if the X-axis is visible.',
    default: 'false',
  },
  {
    id: 20,
    propsName: 'showYAxis',
    propsType: 'boolean',
    propsDescription: 'Determines if the Y-axis is visible.',
    default: 'false',
  },
  {
    id: 21,
    propsName: 'width',
    propsType: 'number',
    propsDescription: 'Width of the chart.',
    default: '600',
  },
  {
    id: 22,
    propsName: 'XAxisDataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the X-axis data.',
    default: 'None',
  },
  {
    id: 23,
    propsName: 'YAxisDataKey',
    propsType: 'string',
    propsDescription: 'Key in the data array for the Y-axis data.',
    default: 'None',
  },
  {
    id: 25,
    propsName: 'tooltipBtnStyle',
    propsType: 'string',
    propsDescription: 'Custom style of the tooltip.',
    default: 'None',
  },
  {
    id: 26,
    propsName: 'lineType',
    propsType: 'CurveType',
    propsDescription: 'Curve type from recharts.',
    default: 'monotone',
  },
  {
    id: 27,
    propsName: 'strokeWidth',
    propsType: 'number',
    propsDescription: 'How will be the stoke width of the line.',
    default: '2',
  },
]
